# Use container-based infrastructure
sudo: false

# Handle git submodules yourself
git:
  submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - openssl aes-256-cbc -K $encrypted_21bd84d1dece_key -iv $encrypted_21bd84d1dece_iv -in travis/travis.tar -out travis/unsafe.travis.tar -d
  - tar -xvf travis/unsafe.travis.tar -C travis/
  - cp travis/unsafe.travis/unsafe.credentials.sbt ./unsafe.credentials.sbt
  - eval "$(ssh-agent -s)"
  - ssh-add travis/unsafe.travis/unsafe.combust.git

language: scala
scala:
  - 2.11.8

script:
  - travis/travis.sh

notifications:
  on_success: change
  on_failure: always
  email: true

jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
