# Use container-based infrastructure
sudo: false

language: scala
scala:
  - 2.11.8

script:
  - travis/travis.sh

notifications:
  on_success: change
  on_failure: always
  email: true

jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
